In [1]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder

data = asarray([['red'], ['red'], ['blue'], ['green'], ['while'], ['green'], ['black']])
print(data)

[['red']
 ['red']
 ['blue']
 ['green']
 ['while']
 ['green']
 ['black']]


In [4]:
encoder = OneHotEncoder(sparse=False)
onehot = encoder.fit_transform(data)
print(onehot)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [6]:
#Using pandas
import pandas as pd
s = pd.DataFrame(data)
s

0
0    red
1    red
2   blue
3  green
4  while
5  green
6  black

In [7]:
pd.get_dummies(s)

0_black  0_blue  0_green  0_red  0_while
0        0       0        0      1        0
1        0       0        0      1        0
2        0       1        0      0        0
3        0       0        1      0        0
4        0       0        0      0        1
5        0       0        1      0        0
6        1       0        0      0        0